### ISSUE TITLE
Reader: Followed Sites can have an unmarked gap in content

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#7430]
It seems there is a situation where the followed sites feed can have an unmarked gap in content.  As observed in a user's feed, the user was following 100s of blogs.  When returning to the followed sites stream after several hours new content would sync but there would be a gap of several hours between the new posts and the previously cached content and no gap button was displayed. 

I was able to reproduce this in the simulator by fetching the list of posts...then returning to the simulator after three or so hours.  

The causes is currently unclear... it might be due to an issue in the app code... it might be due to something with the api.

**Comment by designsimply** [comment]
This came up in another mobile request with the following description:

<blockquote>For example, I’ll see a post in my Reader that says it was posted 8 hours ago and the next post says it was published 3 hours ago…a 5 hour gap. But when I open up Safari or Chrome on my iPhone and log into WordPress and go to the reader, there is no such gap. All the “missing” posts between 8 hours ago and 3 hours ago are there.</blockquote>

<sup>(internal references: p4a5px-2mT-p2, 1852243-zen)</sup>

**Comment by designsimply** [comment]
@aerych can you take a look at this when you have a chance? It was recently fixed for WPAndroid via https://github.com/wordpress-mobile/WordPress-Android/issues/5491 🎉 

<sub>(internal reference: noting that p77Llu-74g-p2 may have some relevant discussion around pagination & sync)</sub>

**Comment by aerych** [comment]
Potentially fixed with #11553 but testing this is wonky so I want to spend a little more time with it to be sure.

**Comment by thehenrybyrd** [comment]
User came back to ask about this in 2028689-zen. It looks like https://github.com/wordpress-mobile/WordPress-iOS/pull/11553 will go out with 12.4. @aerych what's our confidence level with the fix?

**Comment by designsimply** [comment]
@thehenrybyrd there is not a guarantee this issue will fix the case noted by the user in 2028689-zen but since there was a recent attempt to fix the problem that shipped with 12.4 it would be good to let that user know what was updated, that the update was shipped on 2019-05-20, and that if they're still experiencing problems then we may want to create a new issue with steps to reproduce that are as detailed as we can come up with based on their past reports.

**Comment by designsimply** [comment]
@thehenrybyrd can you check back in with that user who reported seeing gaps in content for posts in the Reader? We are wanting to find out if the potential fix in #11553 that shipped in 12.4 was helpful for them.

**Comment by pmciano** [comment]
The user from 2266520-zen and 2028689-zen has come back with the following:

> Thanks for reaching out to me. The issue has been resolved. There is still a gap when I first go to the reader, but then the message “Loading More Posts” appears and the gap is filled in.
>
> I am having two other problems with the latest version of the iOS app, however. When I read posts in the app, my Reblog button isn’t working. And when I tried to open up a ticket to report the issue, I can’t send it. Can these tow issues (Reblog button and opening a help ticket) be addressed?

I've asked them to send a copy of the app log via our Contact Form.

**Comment by designsimply** [comment]
@pmciano thank you for the follow-up! Can you please file the Reblog button issue as a new GitHub issue (let me know if you need help with that) and please add the quoted part about not being able to send a message to support via the app and the Zendesk shorthand reference number in a comment at https://github.com/wordpress-mobile/WordPress-iOS/issues/12297 so we have made sure to note both of those additional reports of problems in the right places.

**Comment by designsimply** [comment]
@aerych ok to close since the person who reported the issue in both comments above has noted the Reader gaps are fixed in their case or would you like more confirmation than that one case?

**Comment by aerych** [comment]
Let's close it! :)  Thanks everyone! 🙇

**Comment by pmciano** [comment]
@designsimply 

> Can you please file the Reblog button issue as a new GitHub issue (let me know if you need help with that)

Done #12299

> please add the quoted part about not being able to send a message to support via the app and the Zendesk shorthand reference number in a comment at #12297 so we have made sure to note both of those additional reports of problems in the right places.

And [done](https://github.com/wordpress-mobile/WordPress-iOS/issues/12297#issuecomment-520601224).
