### ISSUE TITLE
Aztec: VideoPress shortcode not being added to posts.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#7507]
As reported by a tester:

> Video uploads. Love how smooth these are, just like adding a photo , but the VideoPress shortcode is not being added to the post. Instead, just a link to the .mp4 video is shown and I need to edit the recently published post to add the VideoPress code instead of a link.

**Comment by SergioEstevao** [comment]
Does this happens on the 8.0 version?

**Comment by SergioEstevao** [comment]
This was a know issue on 7.9 but I think it was fixed on 8.0

**Comment by diegoreymendez** [comment]
@SergioEstevao - Don't have details about that, so we're going to need to test and try to reproduce.  This was reported through mobilerequests.

**Comment by lschuyler** [comment]
I'll test again this week with 8.0 and update here. Thanks!

**Comment by lschuyler** [comment]
This is still happening in 8.0.0.20170712.

I uploaded a video through the app and expected a VideoPress link to be inserted into the post.

Instead, a link is put into the post in this format:

https://lisa.blog/img_1231-mp4/

which isn't a proper path since the video is on VideoPress/WPCOM. I have to save the draft, and go into my Media Library on my desktop to get the VideoPress shortcode link to replace it with.

**Comment by diegoreymendez** [comment]
cc @SergioEstevao ^

**Comment by SergioEstevao** [comment]
Hi Lisa,

Can you provide me details about the site? is this a WP.com or jetpack site?

Cheers,

Sergio

**Comment by lschuyler** [comment]
Sure!

Jetpack site hosted at Pressable.
Professional JP Plan
https://Lisa.blog
WP 4.8
JP 5.1

Let me know if I can help further.

**Comment by SergioEstevao** [comment]
Thanks for the info Lisa,

Tell me one thing if you use the old hybrid editor? Does it work ok?

Trying to find if the error is on the Editor or in the network code.

Thanks!

**Comment by lschuyler** [comment]
Switched the app from Beta editor to Visual (is that what you meant?) and the same issue occurred - no VideoPress shortcode inserted into the post when I uploaded the video with with the app, just the broken link was inserted into the post.

**Comment by SergioEstevao** [comment]
So I investigated the issue, and it the problem is coming from the REST API response, for Jetpack connected sites, when doing site/XXX/media/new.

I raised the issue with the Jetpack crew and I'm waiting for their answers.

**Comment by SergioEstevao** [comment]
Lisa we submitted an patch to the Jetpack server code that should fix this.
Do you mind to test it again?

**Comment by lschuyler** [comment]
Just tested and it worked as expected! Thanks for the quick fix!

**Comment by diegoreymendez** [comment]
Nice work @SergioEstevao.  Closing this.
