### ISSUE TITLE
Login: Improve xmlrpc discovery to better detect wpcom sites. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#7586]
While testing @rachelmcr identified a few cases where a wpcom user might fail to log in via the self-hosted flow. 

Scenario 1:  A wpcom user with a mapped domain and 2fa enabled. Rather than get the screen to enter their 2fa code they are prompted to enter an application password. This looks due to the call to wp.getOptions in `[LoginFacade loginToSelfHosted:]` -- which would identify the site as a wpcom site -- failing due to the lack of an application password.

Scenario 2: A Jetpack user that has enabled SSO, and in particular a WordPress.com Business customer who only knows their wpcom credentials, would be unable to sign in via this flow.

There may be other cases, but both scenarios could be resolved by querying `/connect/site-info` as the first step in xmlrpc endpoint discovery to identify a wpcom site -- so this is one potential fix.

**Comment by designsimply** [comment]
> Scenario 1: A wpcom user with a mapped domain and 2fa enabled. Rather than get the screen to enter their 2fa code they are prompted to enter an application password.

Steps to reproduce:

1. Start with a WordPress.com site with any plan purchased and a domain credit pending.
1. On the web, go to Profile > Security > Two-Step Authentication and enable 2FA.
1. On the app, log out (if already logged in).
1. Go to My Sites > Register Domain and complete the domain registration flow.
1. Log out.
1. Log back in again and check to see if you are prompted for a 2FA code.

**Result:** I was prompted for a 2FA code as expected. ([43s](https://cloudup.com/cgUJxAf4bnv))

Scenario 1 looks 👍 now.

**Comment by designsimply** [comment]
> Scenario 2: A Jetpack user that has enabled SSO, and in particular a WordPress.com Business customer who only knows their wpcom credentials, would be unable to sign in via this flow.

1. Setup a Jetpack site.
1. On the web, go to Jetpack > Settings, search for "SSO".
1. Enable the option to "Allow users to log in to this site using WordPress.com accounts".
1. (If needed) go to Jetpack and check to see which WP.com user is connected.
1. Try to log in to the app as the user from the previous step.

**Result:** the log in worked as expected.

1. Setup a WordPress.com Business site.
1. Log out of the app.
1. Log back in to the app as the owner of the WordPress.com Business site setup in step 1.

**Result:** the log in worked as expected.

Scenario 1 looks 👍 to me.

**Comment by designsimply** [comment]
> There may be other cases

Because [a lot](https://github.com/wordpress-mobile/WordPress-iOS/pulls?q=is%3Apr+label%3ALogin+closed%3A2017-07-20..2019-11-29+sort%3Acreated-asc) of work has been done on `Login` since the time this post was originally created and because the two scenarios mentioned have been fixed, let's close this issue as fixed. Please re-open or re-report if this comes up again though!

**Comment by rachelmcr** [comment]
These two scenarios are not yet fixed — they are still an issue when logging in via the self-hosted (site address) flow. To reproduce, when logging in to the app be sure to follow these steps:

1. Select "Log In."
2. Select "Or log in by entering your site address" (not the "Continue with WordPress.com" option).
3. Enter your site address.
4. Enter your WordPress.com account credentials.

**Comment by designsimply** [comment]
Thanks for the update. I had the steps totally wrong before! I tested again actually using the custom domain in the "enter your site address" login flow this time and could replicate the bug:

To prepare:

* Create a WordPress.com site and purchase any plan.
* Set up a custom domain as the primary domain.
* Enable two-step authentication for the site owner.

To test:

1. Tap Log in.
1. Tap "Or log in by entering your site address".
1. Enter the custom domain for your site.
1. Enter your WordPress.com account credentials.

Results: after entering a custom domain for a WordPress.com site with WordPress.com account credentials into the self-hosted "enter a site address" login flow, I am unable to proceed past entering a password and see an error or a notice. ([53s](https://cloudup.com/cgOem1tw4pV), [26s](https://cloudup.com/c0HzajBHwuT))

I see this error for a WordPress.com site with a custom domain:

> It looks like this username/password isn't associated with this site.

<img src="https://user-images.githubusercontent.com/1119271/70184677-8e3d0500-16a5-11ea-85eb-114eded4f1fb.png" width="270" alt="it-looks-like-this-username-password-isnt-associated-with-this-site">
<sup>Tested with WPiOS 13.8.0.0 TestFlight beta on iPhone 6S iOS 13.2.3.</sup>

```
2019-12-04 14:38:24:733 🔵 Tracked: application_opened
2019-12-04 14:38:25:220 Insights: Finished fetching post stats.
2019-12-04 14:38:25:451 Stats: Insights Overview fetching operations finished.
2019-12-04 14:38:28:734 Assume the given url is the home page and XML-RPC sits at /xmlrpc.php
2019-12-04 14:38:29:241 🔵 Tracked: login_failed_to_login <error_code: 403, error_description: Error Domain=WPXMLRPCFaultError Code=403 "Incorrect username or password." UserInfo={WordPressOrgXMLRPCApiErrorKeyData={length = 403, bytes = 0x3c3f786d 6c207665 7273696f 6e3d2231 ... 73706f6e 73653e0a }, NSLocalizedDescription=Incorrect username or password., WordPressOrgXMLRPCApiErrorKeyDataString=<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
  <fault>
    <value>
      <struct>
       }, error_domain: WPXMLRPCFaultError>
2019-12-04 14:38:39:895 TracksService sendQueuedEvents completed. Sent 2 events.
2019-12-04 14:50:19:773 <WordPress.WordPressAppDelegate: 0x281ec6500> applicationWillResignActive(_:)
2019-12-04 14:50:20:140 <WordPress.WordPressAppDelegate: 0x281ec6500> applicationDidEnterBackground(_:)
2019-12-04 14:50:20:144 🔵 Tracked: application_closed <last_visible_screen: Login View, time_in_app: 715>

```

I see this notice for a WordPress.com Business account:

> This account has two step authentication enabled. Please configure an application-specific password to use with this application.

<img src="https://user-images.githubusercontent.com/1119271/70182916-09042100-16a2-11ea-87e2-07fd0e9f33ba.png" width="270" alt="login-stuck">
<sup>Tested with WPiOS 13.8.0.0 TestFlight beta on iPhone 6S iOS 13.2.3.</sup>

```
2019-12-04 14:14:13:167 🔵 Tracked: login_accessed
2019-12-04 14:14:13:262 Unable to unregister push for Device ID 33154879: Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://public-api.wordpress.com/rest/v1.1/devices/33154879/delete?locale=en, NSErrorFailingURLKey=https://public-api.wordpress.com/rest/v1.1/devices/33154879/delete?locale=en, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <B55ED08D-ED27-4263-B760-AA9E99FE15FA>.<35>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <B55ED08D-ED27-4263-B760-AA9E99FE15FA>.<35>, NSLocalizedDescription=cancelled}
2019-12-04 14:14:13:362 🔵 Tracked: login_prologue_viewed
2019-12-04 14:14:13:380 Could not sync sites: Optional(Error Domain=WordPressKit.WordPressComRestApiError Code=2 "An active access token must be used to query information about the current user." UserInfo={NSLocalizedDescription=An active access token must be used to query information about the current user., WordPressComRestApiErrorMessageKey=An active access token must be used to query information about the current user., WordPressComRestApiErrorCodeKey=authorization_required})
2019-12-04 14:14:19:666 🔵 Tracked: login_url_form_viewed
2019-12-04 14:14:21:782 TracksService sendQueuedEvents completed. Sent 4 events.
2019-12-04 14:14:30:472 Assume the given url is the home page and XML-RPC sits at /xmlrpc.php
2019-12-04 14:14:31:999 🔵 Tracked: login_username_password_form_viewed
2019-12-04 14:14:36:891 TracksService sendQueuedEvents completed. Sent 1 events.
2019-12-04 14:14:39:405 Assume the given url is the home page and XML-RPC sits at /xmlrpc.php
2019-12-04 14:14:40:092 🔵 Tracked: login_failed_to_login <error_code: 425, error_description: Error Domain=WPXMLRPCFaultError Code=425 "This account has two step authentication enabled. Please configure an application-specific password to use with this application." UserInfo={WordPressOrgXMLRPCApiErrorKeyData={length = 501, bytes = 0x3c3f786d 6c207665 7273696f 6e3d2231 ... 73706f6e 73653e0a }, NSLocalizedDescription=This account has two step authentication enabled. Please configure an application-specific password to use with this application., WordPressOrgXMLRPCApiErrorKeyDataString=<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
  <fault>
    <value>
      <struct>
       }, error_domain: WPXMLRPCFaultError>
2019-12-04 14:14:40:115 This account has two step authentication enabled. Please configure an application-specific password to use with this application.
```

**Comment by kean** [comment]
This will be addressed in the upcoming releases thanks to a web-based login. I don't think we are using this issue to track it, so I'm going to close it so we don't forget.
