### ISSUE TITLE
Editor: site selector/dropdown arrow changes place after changing post settings

### ISSUE THREAD

**Issue by alisterscott** [wordpress-mobile/WordPress-iOS#8791]
In 9.5 after opening the post settings the site selector arrow changes sides.

I found this #dogfooding

### Steps to reproduce the behavior

1. Start a new post
2. Look at site selector
2. Open post options
3. Close post options
4. Look at site selector

##### Tested on iPhone 7 Plus, iOS 11.2.6, WP Internal 9.5.0.20180227 

![fullsizeoutput_106f0](https://user-images.githubusercontent.com/128826/36952712-3f82ad72-205f-11e8-8926-2617f6c42154.jpeg)

Could not reproduce in WPiOS 9.4 (App Store) on same device:

![fullsizeoutput_106f1](https://user-images.githubusercontent.com/128826/36952716-4a0fd576-205f-11e8-84a9-3dff0aa228fe.jpeg)

**Comment by elibud** [comment]
@etoledom could this be related to the RTL work you were doing?

**Comment by frosty** [comment]
@elibud This looks the same as https://github.com/wordpress-mobile/WordPress-iOS/issues/8707, which has been resolved in `develop`. Should we pull it into `release`?

**Comment by elibud** [comment]
Yes please lets add it to `release/9.5`.

**Comment by frosty** [comment]
@elibud Sorry, my bad 🤦‍♂️ The fix is already present in 9.5. I can confirm this situation is happening for me on `develop`. @etoledom any ideas?

**Comment by elibud** [comment]
Still happening on `9.5` too, in case that was not clear, that's where the report is coming from.

**Comment by frosty** [comment]
@elibud Yep, I understood! I originally though the previous fix wasn't in 9.5, but it is – so this is definitely unexpected! Hence the ping for Eduardo :)

**Comment by etoledom** [comment]
Oh no! That change is giving more problems than fixing them. 

I have an idea about what could be happening, I think it’s related with the previews ‘fix’.

I’ll check it out 👍
